---
kernel_built_image: 'arch/x86/boot/bzImage'
kernel_enable_options:
  - '64BIT'               # required for 64bit support
  - 'BINFMT_ELF'          # required to run, y'know, stuff
  - 'BINFMT_SCRIPT'       # required to execute runit stage scripts
  - 'EARLY_PRINTK'        # required to debug early kernel messages
  - 'TTY'                 # required to see/type anything
  - 'SERIAL_8250'         # required for serial console
  - 'SERIAL_8250_CONSOLE' # required for serial console
  - 'VGA_CONSOLE'         # required to render text on VGA hardware
  - 'BLK_DEV_INITRD'      # required for initrd to work
  - 'DEVTMPFS'            # required for tmpfs
  - 'DEVTMPFS_MOUNT'      # required for tmpfs
  - 'TMPFS'               # required for tmpfs
  - 'TMPFS_POSIX_ACL'     # not required but highly recommended
  - 'TMPFS_XATTR'         # not required but highly recommended
  - 'VT'                  # required for virtual terminals
  - 'RTC_CLASS'           # required for hwclock
  - 'RTC_INTF_DEV'        # required for hwclock
  - 'RTC_DRV_CMOS'        # required for hwclock
  - 'NET'                 # required for networking
  - 'INET'                # required for networking
  - 'NETDEVICES'          # required for networking
  - 'ETHERNET'            # required for networking
  - 'IP_PNP'              # required for kernel IP assignment at boot
  - 'PM'                  # required for ACPI
  - 'ACPI'                # required for power-off ACPI events
  - 'PCI'                 # required to enumerate hardware
  - 'VIRTIO_MENU'         # required for the virtio subsystem
  - 'VIRTIO_PCI'          # required to find virtio devices
  - 'VIRTIO_NET'          # required for virtio networking
  - 'E1000'               # required for Intel PRO/1000 GbE
  - 'E1000E'              # required for PCIe Intel GbE NICs
  - '8139CP'              # required for older Realtek NICs
  - 'R8169'               # required for PCIe Realtek GbE NICs
  - 'IGC'                 # required for modern Intel 2.5GbE
  - 'IGB'                 # required for modern Intel GbE
  - 'PACKET'              # required for raw sockets
  - 'INPUT'               # required for the input subsystem
  - 'INPUT_KEYBOARD'      # required for keyboards
  - 'SERIO'               # required for serial I/O bus
  - 'SERIO_I8042'         # required for the keyboard controller
  - 'KEYBOARD_ATKBD'      # required for the keyboard protocol
  - 'BLOCK'               # required for the block device subsystem
  - 'BLK_DEV'             # required for generic block device support
  - 'PARTITION_ADVANCED'  # required for reading disk partition tables
  - 'MSDOS_PARTITION'     # required for reading traditional MBRs
  - 'EFI_PARTITION'       # required for modern GPT partition tables
  - 'VIRTIO_BLK'          # required for VirtIO block device driver
  - 'ATA'                 # required for the ATA/SATA subsystem
  - 'SATA_AHCI'           # required for AHCI SATA
  - 'BLK_DEV_SD'          # required for ATA as SCSI (/dev/sd)
  - 'EXT4_FS'             # required for ext2, ext3, and ext4
  - 'FS_MBCACHE'          # auto-selected by ext4
  - 'JBD2'                # auto-selected by ext4
  - 'XFS_FS'              # required for XFS
  - 'LIBCRC32C'           # auto-selected by xfs
  - 'CRYPTO_CRC32C'       # auto-selected by xfs
  - 'EXPORTFS'            # auto-selected by xfs
  - 'SCSI'                # required for Core SCSI subsystem
  - 'SCSI_LOWLEVEL'       # required for low-level SCSI drivers
  - 'SCSI_VIRTIO'         # required for VirtIO-SCSI
  - 'SCSI_LSI53C895A'     # required for QEMU's legacy SCSI controller
  - 'USB_SUPPORT'         # required for USB menu/subsystem
  - 'USB'                 # required for Core USB driver
  - 'USB_PCI'             # required for USB controllers on PCI bus
  #- 'USB_ANNOUNCE_NEW_DEVICES' # Useful for debugging: prints USB devices to dmesg on plug
  - 'USB_XHCI_HCD'        # required for USB 3.0 (xHCI) controller
  - 'USB_EHCI_HCD'        # required for USB 2.0 (EHCI) controller
  - 'USB_STORAGE'         # required for USB flash/external drives
kernel_finger_url: 'https://www.kernel.org/finger_banner'
kernel_src_domain: 'git.kernel.org'
kernel_src_path: '/pub/scm/linux/kernel/git/stable/linux-stable.git'
...
# vim: set filetype=yaml
