---
kernel_built_image: 'arch/x86/boot/bzImage'
kernel_enable_options:
  - '64BIT'
  - 'BLK_DEV_INITRD'
  - 'BINFMT_ELF'
  - 'TTY'
  - 'VT'
  - 'SERIAL_8250'
  - 'EARLY_PRINTK'
  - 'SERIAL_8250_CONSOLE'
  - 'CONFIG_DEVTMPFS'
  - 'DEVTMPFS_MOUNT'
kernel_finger_url: 'https://www.kernel.org/finger_banner'
kernel_src_domain: 'git.kernel.org'
kernel_src_path: '/pub/scm/linux/kernel/git/stable/linux-stable.git'
...
# vim: set filetype=yaml
