---
services:
  - 'get-hostname'
  - 'single-shell'
  - 'udhcpc'
services_dhcp_lease_s: 3600
services_log: |
  #!/bin/sh
  exec logger -t {{ item }}
services_run: '/etc/sv/{{ item }}/run'
...
# vim: set filetype=yaml
