---
mkisofs_confs:
  - 'isolinux.cfg'
mkisofs_files:
  - '/usr/lib/ISOLINUX/isolinux.bin'
  - '/usr/lib/syslinux/modules/bios/ldlinux.c32'
mkisofs_iso_filename: 'smallest.iso'
...
# vim: set filetype=yaml
