---
- name: 'Linux'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  gather_facts: yes
  vars:
    workdir: 'source/kernel'
    outputdir: 'output/boot'
    dirs:
      - '{{ workdir }}'
      - '{{ outputdir }}'
  tags:
    - 'never'
    - 'linux'
    - 'kernel'
  roles:
    - 'kernel_build'

- name: 'busybox'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  gather_facts: yes
  vars:
    workdir: 'source/busybox'
    outputdir: 'source/initramfs'
    dirs:
      - '{{ workdir }}'
      - '{{ outputdir }}/bin'
      - '{{ outputdir }}/sbin'
      - '{{ outputdir }}/usr/bin'
      - '{{ outputdir }}/usr/sbin'
  tags:
    - 'never'
    - 'busybox'
    - 'shell'
  roles:
    - 'busybox_build'

- name: 'xfsprogs'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  gather_facts: yes
  vars:
    workdir: 'source/xfsprogs'
    outputdir: 'source/initramfs'
    dirs:
      - '{{ workdir }}'
      - '{{ outputdir }}/usr/bin'
  tags:
    - 'never'
    - 'xfsprogs'
    - 'xfs'
  roles:
    - 'xfsprogs_build'

- name: 'jq'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  gather_facts: yes
  vars:
    workdir: 'source/jq'
    outputdir: 'source/initramfs/usr/bin'
    dirs:
      - '{{ workdir }}'
      - '{{ outputdir }}'
  tags:
    - 'never'
    - 'json'
    - 'jq'
  roles:
    - 'jq_build'

- name: 'util-linux'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  gather_facts: no
  vars:
    workdir: 'source/util-linux'
    outputdir: 'source/initramfs/usr/bin'
    dirs:
      - '{{ workdir }}'
      - '{{ outputdir }}'
  tags:
    - 'never'
    - 'util-linux'
    - 'util'
  roles:
    - 'util-linux_build'

- name: 'runit'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  gather_facts: yes
  vars:
    workdir: 'source/runit'
    outputdir: 'source/initramfs'
    dirs:
      - '{{ workdir }}'
      - '{{ outputdir }}/bin'
      - '{{ outputdir }}/etc/runit'
      - '{{ outputdir }}/etc/sv'
      - '{{ outputdir }}/var/service'
  tags:
    - 'never'
    - 'runit'
    - 'init'
  roles:
    - 'runit_build'
    - 'runit_services_create'

- name: 'initramfs'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  gather_facts: no
  vars:
    workdir: 'source/initramfs'
    outputdir: 'output/boot'
    dirs:
      - '{{ workdir }}/dev'
      - '{{ workdir }}/etc'
      - '{{ workdir }}/opt'
      - '{{ workdir }}/proc'
      - '{{ workdir }}/sys'
      - '{{ workdir }}/root'
      - '{{ workdir }}/sbin'
      - '{{ workdir }}/usr/bin'
      - '{{ workdir }}/usr/sbin'
      - '{{ workdir }}/usr/share/udhcpc'
      - '{{ outputdir }}'
      - '{{ outputdir }}/isolinux'
  tags:
    - 'initramfs'
    - 'initrd'
  roles:
    - 'system_files_create'
    - 'initramfs_build'

- name: 'mkisofs'
  hosts: 'all'
  connection: 'local'
  run_once: yes
  gather_facts: no
  vars:
    workdir: 'source/initramfs'
    outputdir: 'output/boot'
    dirs:
      - '{{ workdir }}'
      - '{{ outputdir }}'
  tags:
    - 'mkisofs'
    - 'iso'
  roles:
    - 'iso_build'
...
# vim: set filetype=yaml
