---
# TODO maybe de-template this, too smart
- name: 'Templates'
  loop: '{{ initramfs_confs }}'
  template:
    src: '{{ item }}.j2'
    dest: '{{ outputdir }}/isolinux/{{ item }}'

# temporarily set mknod u+s to get this task working
- name: 'Create dev nodes'
  loop:
    - { path: '/dev/null', type: 'c', major: 1, minor: 3 }
    - { path: '/dev/zero', type: 'c', major: 1, minor: 5 }
    - { path: '/dev/random', type: 'c', major: 1, minor: 8 }
    - { path: '/dev/console', type: 'c', major: 5, minor: 1 }
    - { path: '/dev/tty', type: 'c', major: 5, minor: 0 }
  command:
    creates: '{{ workdir }}/{{ item.path[1:] }}'
    argv:
      - 'mknod'
      - '-m'
      - '0666'
      - '{{ workdir }}/{{ item.path[1:] }}'
      - '{{ item.type }}'
      - '{{ item.major }}'
      - '{{ item.minor }}'

# TODO: make module
- name: 'Pack initramfs archive'
  shell: |
    set -o pipefail
    export LC_ALL=C LANG=C
    find . -print0 | cpio --null -ov --format=newc --owner root:root | gzip -9 > ../../{{ outputdir }}/initrd.img
  args:
    chdir: '{{ workdir }}'
    executable: '/bin/bash'
...
# vim: set filetype=yaml
